
version: '2'

services:
  # spark:
  #   image: docker.io/bitnami/spark:3
  #   environment:
  #     - SPARK_MODE=master
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #   ports:
  #     - '8080:8080'
  seisspark-worker-1:
    image: seisspark
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash
  seisspark-dev:
    image: seisspark-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '9091:9091'
    depends_on:
      - seisspark-worker-1

      
# services:
#   spark:
#     image: docker.io/bitnami/spark:3
#     environment:
#       - SPARK_MODE=master
#       - SPARK_RPC_AUTHENTICATION_ENABLED=no
#       - SPARK_RPC_ENCRYPTION_ENABLED=no
#       - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#       - SPARK_SSL_ENABLED=no
#     ports:
#       - '8080:8080'
#   spark-worker-1:
#     image: docker.io/bitnami/spark:3
#     environment:
#       - SPARK_MODE=worker
#       - SPARK_MASTER_URL=spark://spark:7077
#       - SPARK_WORKER_MEMORY=1G
#       - SPARK_WORKER_CORES=1
#       - SPARK_RPC_AUTHENTICATION_ENABLED=no
#       - SPARK_RPC_ENCRYPTION_ENABLED=no
#       - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#       - SPARK_SSL_ENABLED=no
#   spark-worker-2:
#     image: docker.io/bitnami/spark:3
#     environment:
#       - SPARK_MODE=worker
#       - SPARK_MASTER_URL=spark://spark:7077
#       - SPARK_WORKER_MEMORY=1G
#       - SPARK_WORKER_CORES=1
#       - SPARK_RPC_AUTHENTICATION_ENABLED=no
#       - SPARK_RPC_ENCRYPTION_ENABLED=no
#       - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#       - SPARK_SSL_ENABLED=no