
version: '2'

services:
  su:
    image: su
    build:
      context: .
      dockerfile: su.Dockerfile
    command: /bin/bash

  seisspark:
    image: seisspark
    build:
      context: ..
      dockerfile: docker/seisspark.Dockerfile
    command: /bin/bash
    depends_on:
      - su
  
  seisspark-service:
    image: seisspark-service
    build:
      context: ..
      dockerfile: docker/service.Dockerfile
    ports:
      - '9091:9091'
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - seisspark
    command: /root/start_service.sh

  spark-master:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
    depends_on:
      - seisspark

  spark-worker-1:
    image: seisspark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - seisspark

  spark-worker-2:
    image: seisspark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - seisspark